# Generated by Django 5.2.1 on 2025-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faceloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceloginlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
